import './globals.css'
import { font } from './font'
import { Header } from './components/Header'

export const metadata = {
  title: 'Countries App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
